### ISSUE TITLE
App crashes on setting up unlock with Biometrics

### ISSUE THREAD

**Issue by Loigzorn** [bitwarden/authenticator-android#100]
### Steps To Reproduce

1. Fresh install of the app, from Github
2. Launch app and go to settings
3. Click on "Unlock with Biometrics"

### Expected Result

The option "Unlock with Biometrics" becomes activated and the option a unlock the app using biometrics becomes available

### Actual Result

The app crashes and the setting "Unlock with Biometrics" is still disabled when launching the app and navigation to the settings again.

### Additional Context

The app probably is not configured for the API level 29 of Android.
The crashing of the app would probably not happen using the app on a newer device. 

### Build Version

2024.04.20 (22)

### Environment Details

- Device: OnePlus5
- OSVersion: API 29, Android 10

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaintPatrck** [comment]
Greetings @Loigzorn,
Thank you for submitting a bug report. The issue has been resolved (see #77) and will be published in our next release.
