### ISSUE TITLE
Button "Add Item" covers last verification code

### ISSUE THREAD

**Issue by mik2003** [bitwarden/authenticator-android#105]
### Steps To Reproduce

1. With a clean installation, add eight (8) new items (might depend on screen size).

### Expected Result

I expect each of the items verification code to be visible (or to at least be able to scroll to see the last item's verification code).

### Actual Result

Adding exactly 8 items has just enough to reach the bottom of the screen, thus the last item's verification code becomes obscured by the "Add Item" button, and not enough items are present to allow scrolling. As a temporary fix I added a dummy item that allows me to scroll, and thus reveal the covered code.

### Build Version

2024.5.0 (23)

### Environment Details

- Device: Poco X4 Pro 5G (Model 2201116PG)
- OS Version: MIUI Global 14.0.1 [14.0.1.0(TKCEUXM)] (Android 13 TKQ1.221114.001)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaintPatrck** [comment]
Hi @mik2003,

Thank you for submitting an issue. 

A fix will be available in our next release.
