### ISSUE TITLE
Searching Doesn't Show Code

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [bitwarden/authenticator-android#119]
### Steps To Reproduce

1. Go to the Verification Codes tab
2. Click on the search bar
3. Search for any account
4. Observe the shown item
5. Touch it to try to copy
6. Press and hold to try to open the context menu

### Expected Result

I would expect the searched results to show the verification codes. Touching the searched item would copy that code. And pressing and holding it would open the context menu. 

### Actual Result

The items in the search results do not show the verification codes. Touching it says it copied something but nothing gets copied at all. Pressing and holding it only triggers the same event that touching it does. 

### Screenshots or Videos

![Screenshot_20240611-080513](https://github.com/bitwarden/authenticator-android/assets/34974905/0ef2e5b7-3b4c-49aa-8747-1b4c63255ec4)

### Build Version

2024.5.0 (23)

### Environment Details

- Device: Google Pixel 6a
- OS Version: Android 14, build AP1A.240505.004

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by xortock** [comment]
I encounterd something similar when searching all matching results continue to display the same 2fa codes of 123456. But when scrolling thought the list without searching the correct codes are shown

**Comment by SaintPatrck** [comment]
Fixed with #163.
