### ISSUE TITLE
Tapping to copy TOTP does not work

### ISSUE THREAD

**Issue by RelicCornhusk** [bitwarden/authenticator-android#191]
### Steps To Reproduce

1. Tap a TOTP. It will say it has been copied
3. Attempt to paste in another app

### Expected Result

The TOTP should be pasted

### Actual Result

The clipboard is empty. 

### Additional Context

tapping to copy the TOTP copies it as a password, not allowing it to be pasted elsewhere. Only workaround I've found is tapping the TOTP, then sharing, which displays the TOTP as clear text which can then be copied/pasted elsewhere.  

### Build Version

 Version: 2024.6.2 (340)

### Environment Details

Pixel 6 Pro 
Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by HeyITGuyFixIt** [comment]
I'm also experiencing this on a Pixel 6a, Android 14, app version 2024.6.2 (340).
