### ISSUE TITLE
Space in Manually Entered Key Fails

### ISSUE THREAD

**Issue by MikeA01730** [bitwarden/authenticator-android#199]
### Steps To Reproduce

1. Tap '+' 
2. Tap 'Add item manually' 
3. Type 'iDrive' in name field. 
4. Type '7NLT E5DK QQZG BEIV' in key field.
5. Tap 'Add code'. 

### Expected Result

Item is created. 

### Actual Result

'Key is invalid' is displayed. 

### Additional Context

This key was generated by iDrive. If I remove the spaces the entry is created successfully. 

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.6.2 (340)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
