### ISSUE TITLE
Not copying code when searching for site

### ISSUE THREAD

**Issue by csamolot** [bitwarden/authenticator-android#238]
### Steps To Reproduce

1. Search for website or ID in the search box
2. Click to copy code 
3. Copies item number of instead of the code

### Expected Result

Copying 2fa code

### Actual Result

Copying item number which is a long string

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaintPatrck** [comment]
Hi, @csamolot 

Thank you for reporting your issue.

This was resolved with #163 and will be available in our next release.
