### ISSUE TITLE
Add apk file v2024.12.0

### ISSUE THREAD

**Issue by glasszay** [bitwarden/authenticator-android#304]
### Steps To Reproduce

1. Go to release page
2. Go to Asset section

### Expected Result

There is a apk file

### Actual Result

Only lists source code

### Additional Context

I update Biwarden using Obtainium, which grabs apk from github.

### Build Version

v2024.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaintPatrck** [comment]
Thank you for reporting your issue. Binaries have been attached to the latest release.
