### ISSUE TITLE
Verification code in the bottom hid behind the NEW button

### ISSUE THREAD

**Issue by clav1cula** [bitwarden/authenticator-android#88]
### Steps To Reproduce

Add a list of items until reach the bottom, no more no less.

### Expected Result

All verification codes should be visible

### Actual Result

The big NEW button is on top of the last code in the bottom. Can't scroll the screen, no way to see the code.

### Screenshots or Videos

![image](https://github.com/bitwarden/authenticator-android/assets/6083180/00344f86-0a1d-4f58-8af4-dc4db9f803ea)

### Build Version

2024.5.0(23)

### Environment Details

Device: motorola edge S30
Android version 12

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pratikmhatre** [comment]
@clav1cula can you please assign this issue to me?

**Comment by clav1cula** [comment]
> @clav1cula could you please assign this issue to me?

It seems I don't have permission to assign it to you.
